### ISSUE TITLE
Simplisafe Authentication Button Not Appearing

### ISSUE THREAD

**Issue by EddieDSuza** [hoobs-org/sidecars#5]
**Description**
As part of the authentication process -  A button will launch the authentication process.

But once the plugin is installed - there is no button available to initiate the link process as well as the manual method does not work. 

**Expected behavoir**
Copy and paste the final URL (begins with com.SimpliSafe.mobile://) back into the plugin settings.

**Plugin name**
homebridge-simplisafe3

**Version**
4.0.109

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.
```
10/8/2021, 11:08:46 AMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3ERRORSimpliSafe login failed with error: Error: No authentication credentials detected.
    at SimpliSafe3AuthenticationManager.refreshCredentials (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/common/authManager.js:191:15)
    at new SS3Platform (/var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/index.js:84:41)
    at /usr/src/bridge/server.ts:455:46
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/src/bridge/server.ts:438:31)
    at Server.start (/usr/src/bridge/server.ts:239:69)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
10/8/2021, 11:08:47 AMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3ERRORSee the plugin README for more information on authenticating with SimpliSafe.
10/8/2021, 11:08:47 AMSimplisafe3 Bridgehomebridge-simplisafe3.SimpliSafe 3ERRORInitial accessories refresh failed with error: Error: Not authenticated with SimpliSafe.
    at /var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/index.js:103:56
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```
**Additional context**
This plugin is HOOBS certified.

**Comment by olivier922** [comment]
any fix?
